sudo: required
services:
    - docker

before_install:
  - docker build -t chrishalley86/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true chrishalley86/docker-react npm run test -- --watchAll=false